export const containersTranslations = {
    en: {
        'OBJECT_TYPE_ANY': 'All',
        'OBJECT_TYPE_EMPLOYEE': 'Employee',
        'OBJECT_TYPE_CONTRACTOR': 'Contractor',
        'OBJECT_TYPE_VISITOR': 'Visitor',
        'OBJECT_TYPE_EXCAVATOR': 'Excavator',
        'OBJECT_TYPE_HAUL': 'Haul truck',
        'OBJECT_TYPE_GRADER': 'Grader',
        'OBJECT_TYPE_DRILL': 'Drill',
        'OBJECT_TYPE_DOZER': 'Dozer',
        'OBJECT_TYPE_BUS': 'Bus',
        'OBJECT_TYPE_WATER': 'Water truck',
        'OBJECT_TYPE_BLAST': 'Blast truck',
        'OBJECT_TYPE_SPECIAL': 'Special vehicle',
        'OBJECT_TYPE_LIGHT': 'Light vehicle',
        'OBJECT_TYPE_PUMP': 'Pump',
        'OBJECT_TYPE_GENERATOR': 'Generator',
        'OBJECT_TYPE_CRANE': 'Crane',
        'OBJECT_TYPE_FORK_LIFT': 'Fork lift',
        'OBJECT_TYPE_ACCESS_POINT': 'Access point',
        'OBJECT_TYPE_WELDING': 'Welding',
        'OBJECT_TYPE_DUMPCAR': 'Dumpcar',
        'OBJECT_TYPE_LOCOMOTIVE': 'Locomotive',
        'OBJECT_TYPE_VACUUM': 'Vacuum Truck',
        'OBJECT_TYPE_OTHER': 'Other',
    },
    ru: {
        'OBJECT_TYPE_ANY': 'Все',
        'OBJECT_TYPE_EMPLOYEE': 'Сотрудник',
        'OBJECT_TYPE_CONTRACTOR': 'Подрядчик',
        'OBJECT_TYPE_VISITOR': 'Посетитель',
        'OBJECT_TYPE_EXCAVATOR': 'Экскаватор',
        'OBJECT_TYPE_HAUL': 'Самосвал',
        'OBJECT_TYPE_GRADER': 'Грейдер',
        'OBJECT_TYPE_DRILL': 'Бурстанок',
        'OBJECT_TYPE_DOZER': 'Бульдозер',
        'OBJECT_TYPE_BUS': 'Автобус',
        'OBJECT_TYPE_WATER': 'Поливалка',
        'OBJECT_TYPE_BLAST': 'Зарядная',
        'OBJECT_TYPE_SPECIAL': 'Специальный автомобиль',
        'OBJECT_TYPE_LIGHT': 'Легковой автомобиль',
        'OBJECT_TYPE_PUMP': 'Насос',
        'OBJECT_TYPE_GENERATOR': 'Генератор',
        'OBJECT_TYPE_CRANE': 'Кран',
        'OBJECT_TYPE_FORK_LIFT': 'Подъемник',
        'OBJECT_TYPE_ACCESS_POINT': 'Точка доступа',
        'OBJECT_TYPE_WELDING': 'Сварочный аппарат',
        'OBJECT_TYPE_DUMPCAR': 'Думпкар',
        'OBJECT_TYPE_LOCOMOTIVE': 'Тяговый агрегат',
        'OBJECT_TYPE_VACUUM': 'Вакуумный Автомобиль',
        'OBJECT_TYPE_OTHER': 'Другое',
    }
};
