export const datamonitoringDetailsContainerTranslations = {
    en: {
        'DATAMONITORING_DETAILS_TITLE': 'Details',
        'DATAMONITORING_DETAILS_LOADING': 'Data loading',
        'DATAMONITORING_DETAILS_EMPTY': 'There is no objects in this organization',
        'DATAMONITORING_DETAILS_ERROR': 'Error happened during object loading',
        'DATAMONITORING_DETAILS_ERROR_ACTION_RETRY': 'Retry',
        'DATAMONITORING_DETAILS_EMPTY_OBJECT': 'Object not found in this organization',
        'DATAMONITORING_DETAILS_PER_DAY': 'Per day',
        'DATAMONITORING_DETAILS_TIME_LIVE': 'Current time',
        'DATAMONITORING_DETAILS_TIME_SELECTED': 'Selected time',
        'DATAMONITORING_DETAILS_LOADING_PARAMS': 'Parameters loading',
        'DATAMONITORING_DETAILS_EMPTY_PARAMS': 'There\'s no data for current object in this period',
        'DATAMONITORING_DETAILS_ERROR_PARAMS': 'Something went wrong during loading process',
        'DATAMONITORING_DETAILS_ERROR_SUBTITLE_PARAMS': 'If this error stays, please contact us',
        'VALUE_TYPE_BOOLEAN_YES': 'yes',
        'VALUE_TYPE_BOOLEAN_NO': 'no',
    },
    ru: {
        'DATAMONITORING_DETAILS_TITLE': 'Детальный просмотр',
        'DATAMONITORING_DETAILS_LOADING': 'Загрузка данных',
        'DATAMONITORING_DETAILS_EMPTY': 'На данном сайте нет объектов',
        'DATAMONITORING_DETAILS_ERROR': 'При загрузке объекта произошла ошибка',
        'DATAMONITORING_DETAILS_ERROR_ACTION_RETRY': 'Повторить',
        'DATAMONITORING_DETAILS_EMPTY_OBJECT': 'Объект не найден на текущем сайте',
        'DATAMONITORING_DETAILS_PER_DAY': 'За день',
        'DATAMONITORING_DETAILS_TIME_LIVE': 'Текущее время',
        'DATAMONITORING_DETAILS_TIME_SELECTED': 'Выбранное время',
        'DATAMONITORING_DETAILS_LOADING_PARAMS': 'Загрузка параметров',
        'DATAMONITORING_DETAILS_EMPTY_PARAMS': 'Нет данных для выбранного объекта за данный период',
        'DATAMONITORING_DETAILS_ERROR_PARAMS': 'При загрузке параметров произошел сбой',
        'DATAMONITORING_DETAILS_ERROR_SUBTITLE_PARAMS': 'Если эта ошибка повторяется, пожалуйста, свяжитесь с нами',
        'VALUE_TYPE_BOOLEAN_YES': 'да',
        'VALUE_TYPE_BOOLEAN_NO': 'нет',
    }
};
